### ISSUE TITLE
I cannot publish my changes

### ISSUE THREAD

**Issue by rthompson73** [cop1000/js-koans#19]
When I try to publish my changes from github desktop it says that I do not have permission 
![image](https://cloud.githubusercontent.com/assets/21321004/19750184/22195240-9bbd-11e6-8083-ee8ce597a57e.png)

**Comment by ClicheUsername** [comment]
Trying to publish my branch from Github desktop is giving me the same error.

![image](https://cloud.githubusercontent.com/assets/1264497/19770926/1c200826-9c2f-11e6-9c3e-09e296639aa1.png)

**Comment by hectorsector** [comment]
Apologies @rthompson73 @ClicheUsername try now! If it still doesn't work, drop by #20 where we are troubleshooting similar problems. I'm closing this issue for now, but do comment over there if it still doesn't work.
